#theme = "iTerm-Default"

[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#565656"
blue = "#49a4f8"
cyan = "#99faf2"
green = "#c0e17d"
magenta = "#a47de9"
red = "#ec5357"
white = "#ffffff"
yellow = "#f9da6a"

[colors.normal]
black = "#2e2e2e"
blue = "#47a0f3"
cyan = "#64dbed"
green = "#abe047"
magenta = "#7b5cb0"
red = "#eb4129"
white = "#e5e9f0"
yellow = "#f6c744"

[colors.primary]
background = "#101421"
foreground = "#fffbf6"

[font]
size = 10.0

[font.normal]
family = "DejaVuSansM Nerd Font"

[scrolling]
history = 10000
multiplier = 3

[terminal.shell]
program = "zsh"
args = ["-l", "-c", "tmux -u attach || tmux -u "]

[window]
opacity = 0.8
title = "Terminal"
dimensions = { columns = 73, lines = 20}
